# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    packageType: runtime
    command: 'test'
    projects: '**/*.csproj' # changed this line
    arguments: '--configuration &(buildConfiguration)'
    modifyOutputPath: true # I added this line too

- task: BuildQualityChecks@8
  inputs:
    checkWarnings: true
    warningFailOption: 'fixed'
    warningThreshold: '0'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

