# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCLI@2
  inputs:
    command: test
    projects: '**/*.csproj' # changed this line
    arguments: '--configuration &(buildConfiguration)'
    modifyOutputPath: true # I added this line too
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    packageType: runtime

- task: BuildQualityChecks@8
  inputs:
    checkWarnings: true
    warningFailOption: 'fixed'
    warningThreshold: '0'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
    
- task: DotNetCLI@2
  displayName: 'dotnet publish --configuration &(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SimpleAPI/SimpleAPI.csproj'
    arguments: '--configuration &(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'


